language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data


before_script:
  - git clone https://github.com/opencv/opencv
  - git clone -b bgsegm_java https://github.com/berak/opencv_contrib

script:
  - pwd
  - mkdir ocv
  - cd opencv
  - mkdir build
  - cd build
  - echo -n cmake -DBUILD_LIST=core,imgproc,imgcodecs,video,flann,objdetect,bgsegm,java -WITH_ITT=OFF -WITH_IPP=OFF -DBUILD_IPP_IW=OFF -DBUILD_WITH_DYNAMIC_IPP=OFF -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_examples=OFF -DWITH_OPENEXR=OFF -DBUILD_OPENEXR= >> cm.sh
  - echo -n OFF -DCV_TRACE=OFF -DWITH_TIFF=OFF -DWITH_EXR=OFF  -DCMAKE_INSTALL_PREFIX= >> cm.sh
  - echo -n ../../ocv -DBUILD_ZLIB=ON -DWITH_WEBP=OFF -DWITH_JASPER=>> cm.sh
  - echo -n OFF -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -G \"Unix Makefiles\" .. >> cm.sh
  - cat cm.sh
  - bash cm.sh
  - make -j4
  - make -j4 install
  - ls modules/java/gen
  - cat modules/java/gen/features2d.cpp
  - cat modules/java/gen/bgsegm.txt
  - cat modules/java/gen/bgsegm.log
  - cat modules/java/gen/bgsegm+BackgroundSubtractorCNT.java
  - cat modules/java/gen/video+BackgroundSubtractorMOG2.java
  - cd ..
  - cd ..
  - ls -l
  - ant -DocvJarDir=ocv/share/OpenCV/java -DocvLibDir=ocv/share/OpenCV/java

